# Project info
site_name: Rachel Rigdon's Writing Portfolio
site_url: https://rrigdon.github.io/
site_author: Rachel Rigdon

# Repository
repo_name: rrigdon/rrigdon.github.io
repo_url: https://github.com/rrigdon/rrigdon.github.io

# Copyright
copyright: Copyright &copy; 2023 Rachel Rigdon

# Configuration
theme:
  name: material
  custom_dir: overrides
  logo: rachel_icon.png
  favicon: rachel_icon.png
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.prune
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - toc.follow

  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Plugins
plugins: 
  - search
  - autolinks
  - redirects

# Customization

# extra: 
extra:
  homepage: https://documentation.sailpoint.com
  analytics:
    provider: google
    property: UA-190532626-1
  generator: false
  annotate:
    json: [.s2]


# Extensions

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.keys
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - def_list
  - toc:
      title: On this page
      toc_depth: 3

plugins:
  - search
  - autolinks
  - redirects

  # Page tree
nav:
  - Home: index.md
  - Cloud Governance:
    - cloud_gov/index.md
    - Configuring your CSPs:
      - cloud_gov/csp/index.md
      - Configuring AWS: config_aws.md
      - Configuring Azure Cloud: config_azure.md 
      - Configuring Google Cloud Provider: config_gcp.md
  - Internal Processes:
      - internal/index.md
      - Authoring Your Docs: internal/authoring.md
      - Release Notes: internal/release_notes.md 
    
docs_dir:
  docs

site_dir:
  site
  
extra_css:
  - stylesheets/extra.css

use_directory_urls: true
