# Project info
site_name: Rachel Rigdon's Writing Portfolio
site_url: https://rrigdon.github.io/
site_author: Rachel Rigdon

# Copyright
copyright: Copyright &copy; 2025 Rachel Rigdon

# Configuration
theme:
  name: material
  custom_dir: overrides
  logo: assets/letter_r.png
  favicon: assets/letter_r.png
  icon:
    view: material/linkedin
    edit: material/email
  features:
    - content.code.annotate
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.prune
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - toc.follow
    - announce.dismiss
    - content.action.edit
    - content.action.view


# Plugins
plugins: 
  - search
  - autolinks
  - redirects
  - glightbox


# Customization

# extra: 
extra:
  analytics:
    provider: google
    property: G-V7PBXBTD21
  annotate:
    json: [.s2]
  social:
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/in/rachel-rigdon/


# Extensions

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.keys
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - def_list
  - toc:
      title: On this page
      toc_depth: 3
  
# Page tree
nav:
  - Home: index.md
  - Identity Security: id_security.md
  - Anaconda:
    - anaconda/index.md
    - Conda-build recipes: anaconda/recipe.md
    - Building skeleton packages: anaconda/build-pkgs-skeleton.md
    - Building conda packages: anaconda/building-conda-packages.md
    - Building conda packages from scratch: anaconda/build-pkgs.md
    - Using conda with Travis CI: anaconda/use-conda-with-travis-ci.md
  - Legaltech: disco.md
  - Academic: academic.md

    
docs_dir:
  docs

site_dir:
  site
  
extra_css:
  - stylesheets/extra.css

use_directory_urls: true
